MLR
Enterprise-CMCS/macpro-mdct-mcr pull request #11129
Opened 2023-03-09 14:56 UTC by karla-vm

## Summary

### Description

### Related ticket

### How to test

### Important updates

### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated the documentation, if necessary

2023-03-17 15:27 UTC, ntsummers1 commented
Entering a program doesn't show its name
![Screenshot 2023-03-17 at 11 21 35 AM](https://user-images.githubusercontent.com/19439679/225947418-6e0619e2-51a7-4100-af94-228b6d46cf27.png)

On submission screen the name is undefined as well, and need to change mcpar to mlr
![Screenshot 2023-03-17 at 11 24 48 AM](https://user-images.githubusercontent.com/19439679/225948301-1683f9eb-cccd-4872-8595-37f48d9b3140.png)

Due date is NaNaNa, maybe something more descriptive?

![Screenshot 2023-03-17 at 11 18 10 AM](https://user-images.githubusercontent.com/19439679/225946562-55c1f5a3-a637-4cd4-b1fb-11cf8d45fb72.png)


Probably dont need the exclusion of MCPAR note here as well
![Screenshot 2023-03-17 at 11 20 14 AM](https://user-images.githubusercontent.com/19439679/225947091-99b7a967-00ac-47f9-9347-60913ddcb5f1.png)

Can we update this error message for when a report has been submitted that we can't edit the name? Or to remove that ability if its been submitted?

https://user-images.githubusercontent.com/19439679/225947943-f781fc62-620d-40d4-9ccd-3e95beb8a7a7.mov

Admins can update the resubmission field but not actually save it. Please tell me this isn't autosave failing you 😓 

https://user-images.githubusercontent.com/19439679/225948871-0d51e172-1f0e-4c70-b9a8-422575cfd11f.mov



Double Checking: Should this page show my answers and more yet? Or to be done at a later time?
![Screenshot 2023-03-17 at 11 18 56 AM](https://user-images.githubusercontent.com/19439679/225946735-8ff0a1f2-bf64-4e8a-afbc-2dea9941efde.png)


Should the print screen show the total reports submitted yet? Or to be done at a later time?

![Screenshot 2023-03-17 at 11 17 08 AM](https://user-images.githubusercontent.com/19439679/225946352-b87224de-da23-48b6-bd4e-3f259de05037.png)

2023-03-17 15:28 UTC, ntsummers1 requested changes
See notes above - Feel free to tell me i've overstepped on any of these. Apologies if I have. Overall this is some really awesome work!

2023-03-18 19:20 UTC, braxex commented
@ntsummers1 Great notes above. Will you split those out into individual comments so they can be addressed and closed individually?

2023-03-22 16:03 UTC, ntsummers1 commented
![Screenshot 2023-03-22 at 12 03 10 PM](https://user-images.githubusercontent.com/19439679/226965944-e8cad876-6df7-4221-b940-9b37ed245e96.png)

Should this still have the date and MCPAR section when a user goes to the print view?

2023-03-22 16:04 UTC, ntsummers1 commented
![Screenshot 2023-03-22 at 12 04 07 PM](https://user-images.githubusercontent.com/19439679/226966173-f98d6a2d-8b5c-480e-8399-348d293a40d7.png)

I believe this should say 1 MLR reports total underneath here, could be wrong

2023-03-22 16:09 UTC, oweingrod-coforma commented
> ![Screenshot 2023-03-22 at 12 04 07 PM](https://user-images.githubusercontent.com/19439679/226966173-f98d6a2d-8b5c-480e-8399-348d293a40d7.png)
> 
> I believe this should say 1 MLR reports total underneath here, could be wrong

Currently it shows 0 before you add a program report and then correctly displays the number of reports (but not the reports themselves, that's another ticket).

2023-03-22 16:09 UTC, ntsummers1 commented
![Screenshot 2023-03-22 at 12 07 18 PM](https://user-images.githubusercontent.com/19439679/226967385-07664e31-7cd2-41d3-8e64-cadcbafef77a.png)

These buttons have to be a color contrast issue for accessibility right? Or is it because they are disabled its ok? I suspect we'd have to change the disabled state here to match what the new submission button looks like for mcpar status page or some other variation that design might recommend

2023-03-22 16:10 UTC, oweingrod-coforma commented
> ![Screenshot 2023-03-22 at 12 07 18 PM](https://user-images.githubusercontent.com/19439679/226967385-07664e31-7cd2-41d3-8e64-cadcbafef77a.png)
> 
> These buttons have to be a color contrast issue for accessibility right? Or is it because they are disabled its ok? I suspect we'd have to change the disabled state here to match what the new submission button looks like for mcpar status page or some other variation that design might recommend

That's a good shout, let me check with design

2023-03-22 16:23 UTC, ntsummers1 commented on services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
> +  // TODO: test MLR
Can likely remove this

2023-03-22 16:41 UTC, ntsummers1 submitted a review, later dismissed

2023-03-22 18:31 UTC, merged