multi-choice options to have unique IDs
Enterprise-CMCS/macpro-mdct-mcr pull request #4324
Opened 2022-10-11 17:08 UTC by scwambach

## Description

Radio/checkboxes inputs were sharing IDs which was causing a bug where by clicking the label of a separate list in the same form would cause the previous input to be selected.

https://user-images.githubusercontent.com/8299237/195155377-73f241f0-caae-4e55-9cf9-a9283204e7c1.mov

### How to test

go to `/mcpar/program-level-indicators/availability-and-accessibility/access-measures` or any form with multiple radio or checkbox lists and get clicking on some inputs!

### Changed Dependencies

## Code author checklist
- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [ ] I have added analytics, if necessary
- [ ] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

2022-10-11 17:46 UTC, gmrabian approved these changes
Didn't see any issues - I was wondering if this would be a problem for form updates, but I think this actually is better because then order is irrelevant plus we track form versions per program. Good stuff!

2022-10-11 18:29 UTC, karla-vm approved these changes

2022-10-11 18:29 UTC, karla-vm commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                      "name": "quality/performance-measurement",
We might want to standardize our naming to using just dashes, I worry slashes might cause some trouble in the future.

```suggestion
                      "name": "quality-performance-measurement",
```

2022-10-11 18:29 UTC, karla-vm commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                    "name": "ltss-grievance/appeals-education",
```suggestion
                    "name": "ltss-grievance-appeals-education",
```

2022-10-11 18:29 UTC, karla-vm commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                    "name": "ltss-grievance/appeals-assistance",
```suggestion
                    "name": "ltss-grievance-appeals-assistance",
```

2022-10-11 18:29 UTC, karla-vm commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                    "name": "review/oversight-of-ltss-data",
```suggestion
                    "name": "review-oversight-of-ltss-data",
```

2022-10-11 18:29 UTC, karla-vm commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                    "name": "enrollment-broker/choice-counseling",
```suggestion
                    "name": "enrollment-broker-choice-counseling",
```

2022-10-11 18:29 UTC, karla-vm commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                    "name": "academic/research-organization",
```suggestion
                    "name": "academic-research-organization",
```

2022-10-11 19:41 UTC, braxex reviewed
Just a couple thoughts.

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                      "name": "state-ownershipControlDisclosureWebsite-option-peru",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                      "name": "state-excludedEntityIdentifiedInFederalDatabaseCheck-option-lawn",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                                "name": "state-encounterDataValidationSystemHipaaCompliance-option-moccasin",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                      "name": "program-encounterDataUses-option-misty",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                      "name": "program-encounterDataSubmissionCorrectionPerformanceEvaluationCriteria-option-sea",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                            "name": "accessMeasure-providerType-option-powder",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                            "name": "accessMeasure-providerType-option-gainsboro",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                            "name": "accessMeasure-providerType-option-antique",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                            "name": "accessMeasure-population-option-thistle",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                            "name": "accessMeasure-oversightMethodFrequency-option-dodger",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                        "name": "plan-medicalLossRatioPercentageAggregationLevel-option-cornsilk",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                        "name": "plan-medicalLossRatioPercentageAggregationLevel-option-lace",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                        "name": "qualityMeasure-domain-option-saddle",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                        "name": "qualityMeasure-domain-option-cadet",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                        "name": "qualityMeasure-set-option-deep",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                        "name": "sanction-interventionTopic-option-cadet",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                        "name": "plan-programIntegrityReferralPath-option-floral",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                        "name": "plan-programIntegrityReferralPath-option-dim",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                        "name": "plan-beneficiaryCircumstanceChangeReportingFrequency-option-alice",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                        "name": "plan-beneficiaryCircumstanceChangeReportingFrequency-option-ghost",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 19:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                    "name": "bssEntity-entityType-option-bisque",
Maybe change since it's not immediately recognizable as a color?

2022-10-11 23:28 UTC, braxex reviewed
@scwambach One more comment on parent field id formatting.

2022-10-11 23:28 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                      "name": "state-encounterDataValidationEntity-option-plum",
Sorry I wasn't clearer about the `_` vs. `-` earlier. Using this one as an example, I think this is the format we should go for:
- Keep first parent identical to parent field id: `state_ encounterDataValidationEntity`
- Add `-option:color` or `-option-color` or whatever.

So the final state would be: `state_encounterDataValidationEntity-option-color`

2022-10-11 23:30 UTC, braxex requested changes

2022-10-11 23:30 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                      "name": "state-encounterDataValidationEntity-option-plum",
Sorry I wasn't clearer about the _ vs. - earlier. Using this one as an example, I think this is the format we should go for:

- Keep first parent identical to parent field id: `state_ encounterDataValidationEntity`
- Add `-option-color` or whatever. Actually maybe it's clearer if we use a colon, like `-option:color`

So the final state would be: `state_encounterDataValidationEntity-option:plum`

2022-10-13 19:05 UTC, braxex requested changes

2022-10-13 19:05 UTC, braxex commented on services/ui-src/src/utils/forms/forms.ts
> +      choice.id = `${field.id}-${choice.id}`;
Request: Let's flip these lines so the `choice.name` and `choice.id` are always the same.

2022-10-13 19:08 UTC, braxex approved these changes

2022-10-13 19:36 UTC, merged