Mdct 2102 - PDF: Preview Page setup
Enterprise-CMCS/macpro-mdct-mcr pull request #4920
Opened 2022-11-30 18:40 UTC by scwambach

## Description

Building out the layout for the PDF export page.

Some of the data is visible, some isn't at this point. Subsequent tickets will fill in those gaps.

This is just the basic layout for now.

### How to test

[Figma project](https://www.figma.com/file/GBktI8ZIJM9YYcdNva0ltg/MDCT---MCR?node-id=5725%3A97449&t=DhxXofhAXpK0YBtS-0)

got to `/mcpar/export` after creating and entering a project

### Changed Dependencies

## Code author checklist
- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [ ] I have added analytics, if necessary
- [ ] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

2022-12-02 17:16 UTC, braxex commented
@scwambach We're gonna have PDF/Export use the same kind of feature-branch workflow that we're doing for autosave, so we'll have all PRs point to this new export branch that I just made.

2022-12-02 18:20 UTC, gmrabian reviewed
The browser view is great! Just requesting some cleanup here. Will re-review after

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/app/AppRoutes.tsx
> +          <Route path="/profile" element={<ProfilePage />} />
this somehow got duplicated?

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/pages/Export/McparPdfExport.tsx
> +import addEditProgram from "../../../forms/addEditProgram/addEditProgram.json";
nit: organize these how we organize our other imports

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/pages/Export/McparPdfExport.tsx
> +  const data = useContext(ReportContext);
if we only ever use `report` could we destructure this to go straight to report?

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/pages/Export/McparPdfExport.test.tsx
> +});
make sure to add our usual a11y test in here as well

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/export/StickyBanner.tsx
> +      <p>Click below to export or print MCPAR shown here</p>
Could we use a `Text` tag here to stick with Chakra?

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/export/StickyBanner.tsx
> +      fontSize: "1.3rem",
Let's get these .1 and .3 rem values into real breakpoints (rather than fractions of pixels). Maybe 11.125 and 1.25? Maybe check with design

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +    fontSize: "1.3rem",
same as below - coerce to real pixel breakdown (1rem = 16p)

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/pages/Export/McparPdfExport.tsx
> +export const sxDataTable = {
could we pass this into `FieldsSubsection` rather than exporting it?

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +import { CustomHtmlElement } from "types";
nit: organize and add comments like in other component files

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +import { sxDataTable } from "components/pages/Export/McparPdfExport";
If this is coming from components let's put it in the component import, or else pass it in to the component directly rather than importing

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +        id: string;
nit: put required first

2022-12-02 18:20 UTC, gmrabian commented on services/ui-src/src/components/export/FieldsSubsection.test.tsx
> +});
let's add our usual a11y test at the end here

2022-12-02 20:43 UTC, braxex requested changes

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +  };
Suggestion: I think we should separate the idea of a two-column table from a three-column table entirely so we can avoid having to return sometimes an array of 3 and sometimes an array of 2. Not sure what exactly that would look like.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +    <Box data-testid="fieldsSubSection" mt="2rem" key={content.path}>
Probably don't need the `key` here because you already have it on the parent <FieldsSubsection>.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +      {content.verbiage?.intro.info && (
Suggestion: Destructure `verbiage` and `form` above and then if there's verbiage, check for info and spreadsheet and display.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +          className={isNotDynamicField ? "standard" : "short"}
Question: Is this 2-col vs. 3-col?

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +              field.props ? fieldRowsItems(field) : []
I might be wrong, but I think even if there are no props, we might want to show something for the field. Might be something to look into.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +export { FieldsSubsection };
Convention: Can add `export` to beginning of line 12 to handle it neatly there.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +}
Can probably reuse a type from types/index for this.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/StickyBanner.tsx
> +      <p>Click below to export or print MCPAR shown here</p>
Convention: This should be `<Text />` from Chakra instead.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/StickyBanner.tsx
> +export const StickyBanner = () => {
Let's pass in some text props to this so it doesn't have to just be for MCPAR (planning for MLR/NAAAR needing this too).

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/StickyBanner.tsx
> +
Convention: Organize CSS.
```suggestion
    position: "sticky",
    top: "11.1rem",
    margin: "2rem 0",
    padding: "3rem 2rem",
    background: "white",
    boxShadow: "0px 3px 9px rgba(0, 0, 0, 0.2)",
    textAlign: "center",
```

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/export/StickyBanner.tsx
> +      fontSize: "1.3rem",
Convention: Use a size from theme.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/pages/Export/McparPdfExport.test.tsx
> +const mockContext = {
Can reuse some mocks from setupJest so we're not repeating ourselves here.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/pages/Export/McparPdfExport.tsx
> +      fontSize: "1rem",
Convention: Use size from theme.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/pages/Export/McparPdfExport.tsx
> +    fontSize: "2rem",
Convention: Use size from theme.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/pages/Export/McparPdfExport.tsx
> +import { useContext } from "react";
Nit: Move to top line.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/pages/Export/McparPdfExport.tsx
> +import addEditProgram from "../../../forms/addEditProgram/addEditProgram.json";
Suggestion: For this text and all other text on this page, we should make a separate .json file with text for it so we can provide that json file to the component and that way we can reuse this for MLR and NAAAR in the future as needed.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/pages/Export/McparPdfExport.tsx
> +export const McparPdfExport = () => {
Suggestion: Change name to `ExportedReportPage` or something like that since we'll be using this for other reports, not just MCPAR.

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/pages/Export/McparPdfExport.tsx
> +                  `${data.report.status}`,
Suggestion: Don't need to have these as literals -- they can all just be normal like:
`convertDateUtcToEt(data.report.dueDate),`...

2022-12-02 20:43 UTC, braxex commented on services/ui-src/src/components/pages/Export/McparPdfExport.tsx
> +            {`Managed Care Program Annual Report (MCPAR) for ${data.report.fieldData.stateName}: ${data.report.programName}`}
Suggestion: No need for literals here either.

2022-12-05 16:33 UTC, britt-mo approved these changes

2022-12-05 18:22 UTC, scwambach commented on services/ui-src/src/components/export/FieldsSubsection.tsx
> +          className={isNotDynamicField ? "standard" : "short"}
yes

2022-12-05 19:43 UTC, gmrabian commented on services/ui-src/src/components/pages/Export/ExportedReportPage.test.tsx
> +    expect(results).toHaveNoViolations();
I'd prefer if we split out the a11y tests, but not a big deal either way

2022-12-05 19:48 UTC, gmrabian commented on services/ui-src/src/components/export/ExportedReportSubsection.tsx
> +    return [`<strong>${field.props.label}</strong>`, pareseFieldData(field.id)];
Are we doing dynamic stuff later?

![Screen Shot 2022-12-05 at 2 48 22 PM](https://user-images.githubusercontent.com/57802560/205729527-fc5f1e0c-54a2-4492-9359-25ed486ac7ec.png)
![Screen Shot 2022-12-05 at 2 48 14 PM](https://user-images.githubusercontent.com/57802560/205729548-0b657d85-0652-4b4a-aaee-ab591850b90c.png)

2022-12-05 19:49 UTC, gmrabian reviewed
Few remaining questions

2022-12-06 00:03 UTC, britt-mo commented on services/ui-src/src/utils/other/parsing.ts
> +  // const typeOfData = typeof data;
typo on 'parse'

2022-12-06 15:18 UTC, gmrabian commented on services/ui-src/src/components/export/ExportedReportSubsection.tsx
> +    return [`<strong>${field.props.label}</strong>`, pareseFieldData(field.id)];
note from Scott: to be worked later

2022-12-06 15:47 UTC, gmrabian approved these changes

2022-12-06 15:57 UTC, merged